# Use 'createuser -s postgres' to create a general purpose db (super)user.

development: &default
  adapter: postgresql
  database: plateit_development
  username: postgres
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: plateit_test
  min_messages: warning
